### PR TITLE
upgrade to 2.0.0-beta.12 - angular material and ng - 4.4.x as well

### PR DESCRIPTION
**Pull request by akkumar**
2.0.0-beta.12. ng material deprecated md and replaces with mat. 

Also upgrade to ng 4.4.x as well as angular material requires a minimum of ng 4.4.3 .

### CODE REVIEW

**Comment by akkumar** [comment]
Issue #56 about upgrading ng to 4.4.x also handled as part of ng material upgradation.

**Comment by bfwg** [comment]
Hi @akkumar 
The app top navigation icon and carousel navigation buttons does not look right.

image

Cheers

**Comment by akkumar** [comment]
work in progress. The buttons do not seem to appear yet.

**Comment by akkumar** [comment]
Hi @bfwg - Please check now. MatButtonModule and MatButtonToggleModule imported as well. Should fix the view of the buttons as well.

**Comment by akkumar** [comment]
Eventually - as compared to the custom css (especially the media selectors in css) all over the place - it would be useful to use angular/flex-layout lib . But that is for a different PR I would imagine.

**Comment by bfwg** [comment]
LGTM 👍  nice job.

**Pull request merged**
