### PR TITLE
Pre-npm 4 compatibility

### PR DESCRIPTION
**Pull request by bfwg**
My work place uses npm@3.10.10 and I need to make this library backward compatible with my working environment.

I'm trying to migrate the build scripts from https://github.com/urish/angular2-moment

- Refactor tsconfig.json.
- remove npmignore.
- use prepublish for npm < 4 compatibility.

@akkumar I'm trying to see the `ngc` build result with `npm pack`, but seems like `prepublish` is not getting executed. I don't know where have I done wrong. Can you run the below change in your machine?

### CODE REVIEW

**Comment by akkumar** [comment]
@bfwg - I am able to reproduce the issue with node v6.9.5 ( npm 3.10.10 ) . Unfortunately don't have a fix right away as I am still looking into it. 

Meanwhile - this patch contains way too many changes unrelated to the core issue that I am unable to review/ would not suggest merging at this point.

some suggested course of action: 

* create a new branch - npm3, say off master ( not 'develop' ) so we can work on that branch and I can submit PR-s to that branch to make it npm3 compatible. 

As far as versioning goes - we can have 1.5.x for npm4+ releases ( as it is today) and 1.4.x for npm3 releases when we make one. 

Until then a fallback plan with old npm would be to use 1.4.4 that contains ng4.4.x of course- but should be working with npm3. 

Clearly - we are missing something very minute / trivial for npm3 compatibility (this patch contains too things going on) - so let me know by creating a npm3 branch off master - while we can look into the same and submit/review PR to the same.

**Comment by akkumar** [comment]
Ok - short answer - the patch (for pre-npm-4 only) is available here: 
```json
    "angular2-drag-scroll": "git@github.com:akkumar/angular2-drag-scroll.git#4b75ce23b8ca211c7f64bc008565fd772982e9d3"
```

Do verify this and let me know if it works. 

As mentioned earlier - let us create a separate branch - npm3 or similar - off master- and then I will be able to submit a PR to do that branch to move ahead. 

**warning**: This patch is not directly applicable to master or develop as they deal with different npm versions altogethers. 

The details / diff are available here - https://github.com/akkumar/angular2-drag-scroll/commit/4b75ce23b8ca211c7f64bc008565fd772982e9d3 . 

**Summary**
There is no equivalent of 'prepare' (belonging to the post-npm-4 era) , in the pre-npm-4 era. 

So - preinstall replaces prepare by invoking ngc again. And then, postinstall removes the .ts files and leaves behind the .d.ts files ( because ng5+ does not like .ts to be present in the package ). 

prepublish command is there for compiling before we publish. (for some reason unknown to me, the artifacts are not available at the 'npm i' stage of pre-npm-4 which is why the command is repeated again as preinstall).

Also - .npmignore does not ignore .ts anymore since it is needed at the install ( preinstall / postinstall ) stage in the pre-npm-4 era. 

**LongTerm**

As mentioned earlier - we need to be maintaining 2 different branches, master-> for npm4+ and npm3(say) - > for pre-npm-4 packaging as mentioned above. ( until the point we are ready to move away from pre-npm-4).

We can have 1.5.x and above for npm4+ releases and 1.4.x  versions for pre-npm-4 releases, until the point we are ready to move away from pre-npm-4. 

Let me know once a new branch off master is created and I will be happy to submit a PR to that branch. 
Otherwise - you can follow the link above -  https://github.com/akkumar/angular2-drag-scroll/commit/4b75ce23b8ca211c7f64bc008565fd772982e9d3 and create the patch yourself and ready to go. 

ps: The above PR #77  - imho can be closed since it deals with way too many moving parts to be merged to the tree.

**Comment by bfwg** [comment]
Thanks for a detailed explanation. I totally agree with your point and I have created `npm3` branch for you to post your PR. 

As for long-term: I would suggest using develop branch for anything pre-release and use master branch only for releases. 

develop-> for npm4+ and
master -> for npm4+ release
npm3 - > for pre-npm-4 packaging

Personally, I'm not a big fan of npmignore, maybe we can use the [files](https://docs.npmjs.com/files/package.json#files) entity in package.json. I feel that will be less error-prone.

Closing this PR as @akkumar pointed out that there are too many moving parts.

**Comment by akkumar** [comment]
#81 tracking the issue independently. 

Agree about the develop / master separation of concerns as you had mentioned. 

We can definitely explore the aspect of getting away from .npmignore in favor of files in package.json as applicable

**Comment by akkumar** [comment]
#81 got way too commits. closed the PR . submitted #82 that contains the squashed version to be more readable

**Pull request closed without merging**
