### PR TITLE
prenpm4 more concise commit

### PR DESCRIPTION
**Pull request by akkumar**
Squashed commit version of #81 ( also a follow up of #77 as well )

### CODE REVIEW

**Comment by akkumar** [comment]
Please review and we are good to go here. (with the caveats mentioned in #81 of course ).

**Comment by akkumar** [comment]
"So - finally here the build is green, with some big caveats.

The correct equivalent of of 'prepare' (of the post-npm-4 world) would be 'postinstall' in the pre-npm-4 world since 'ngc' needs to be 'installed' already for it to work. At preinstall stage - ngc is not yet installed so the build would fail in that case.

The initial solution of - deleting the .ts files in the postinstall is a bad idea since it can potentially delete the local .ts files as well during an installation - losing hours of work (in case it was not checked into source control).

Given that we are not deleting .ts files yet, this is good enough to work with pre-npm4 packages but only with ng4.4.x and not ng5 ( that demands strict non-presence of .ts files in the distribution).

Also - given the non-intuitive semantics for the pre-npm-4 world ( that demands ngc transpilation at the install stage as well and not just publish stage as in post-npm-4+ world), we are better off migrating to npm4+ world sooner than later.

If we dont want to migrate - then we can live with ng4.4.x as part of this patch and npm3 branch though." - copied from #81

**Comment by mychalhackman** [comment]
Is the issue really from NG5 or is it from Angular/CLI 1.5.0?
I'm able to install angular2-drag-scroll 1.4.5 with Angular 5.0.1 by reverting @angular/cli to 1.5.0-rc.8

My workplace is using has just upgraded a relatively large project to Angular 5.0.1 that includes angular2-drag-scroll.

**Comment by bfwg** [comment]
@akkumar Sorry for the delayed response. I think we should migrate to use npm4+. As for our work project, @mychalhackman found out that we can use `yarn install` to trigger `prepare` on npm < 4. So maybe we should just update the README.md and use `yarn install` as it will make the library backward compatible.

**Comment by akkumar** [comment]
@mychalhackman - thanks for the correction. Yes- it is more specifically about cli 1.5+ ( which indirectly is needed for ng5 though). 

@bfwg - that would be great. It would save us a ton of headache to ignore this (npm < 4) altogether as we will end up saving a lot of time.  

So - we can just officially ditch this PR and I will be the happiest person if we drop the support for pre-npm-4 :)

**Comment by akkumar** [comment]
We just need a different PR mentioning the instructions / README about doing this with yarn. This PR would be needed no longer.

**Pull request closed without merging**
